# Generated by Django 6.0 on 2026-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(choices=[('LOBBY', 'Kutish zali'), ('NIGHT', 'Tun 🌑'), ('MAFIA', 'Mafia Vaqti 🔫'), ('DOCTOR', 'Doktor Vaqti 💉'), ('DAY', 'Kun ☀️')], default='LOBBY', max_length=20),
        ),
    ]
