# Generated by Django 6.0 on 2026-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='doctor_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='mafia_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='morning_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('MAFIA', 'Mafia 🔫'), ('DOCTOR', 'Doktor 💉'), ('CITIZEN', 'Tinch Aholi 🧔')], max_length=20, null=True),
        ),
    ]
